import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Lang = 'fr' | 'ar';

export const translations = {
  fr: {
    nav: {
      client: "Vue Client",
      merchant: "Commerçant",
      partner: "Partenaire",
      login: "Se connecter",
      partnerSpace: "Espace Partenaire",
      merchantSpace: "Espace Commerçant",
      logout: "Déconnexion",
    },
    landing: {
      badge: "Disponible dès maintenant — Nabeul, Tunisie",
      heroTitle: "La fidélisation client",
      heroAccent: "réinventée",
      heroTitle2: "pour vos commerces",
      heroSub: "Remplacez les cartes papier par une solution digitale moderne. QR code, points, récompenses — tout en un, sans téléchargement.",
      cta1: "Voir le Dashboard",
      cta2: "Vue Client",
      stat1: "Plus de visites répétées",
      stat2: "Téléchargement requis",
      stat3: "Pour démarrer",
      problemTitle: "Les commerces locaux méritent mieux",
      problemSub: "Les méthodes traditionnelles ne fonctionnent plus dans l'économie digitale d'aujourd'hui.",
      problems: [
        { icon: "📋", title: "Cartes papier perdues", desc: "Les clients perdent leurs cartes. Les commerçants perdent des clients." },
        { icon: "📊", title: "Aucune donnée client", desc: "Impossible de comprendre son audience ou personnaliser les offres." },
        { icon: "👁️", title: "Visibilité limitée", desc: "Pas d'avis en ligne, difficile d'attirer de nouveaux clients." },
      ],
      actorsTitle: "Une solution pour chaque acteur",
      actorsSub: "Jigoula.cards connecte clients, commerçants et partenaires dans un écosystème digital.",
      clientRole: "Client",
      clientTitle: "Fidélité sans friction",
      clientDesc: "Scanne le QR code et profite de ses avantages sans application à télécharger.",
      clientFeatures: ["Scan QR instantané", "Suivi points & tampons", "Récompenses automatiques", "Invitation avis Google"],
      merchantRole: "Commerçant",
      merchantTitle: "Dashboard complet",
      merchantDesc: "Gérez votre programme de fidélité et analysez vos performances depuis un dashboard intuitif.",
      merchantFeatures: ["Analytics & statistiques", "Gestion des clients", "QR Code unique", "Points ou tampons", "Avis Google Maps"],
      partnerRole: "Partenaire",
      partnerTitle: "Multi-enseignes",
      partnerDesc: "Regroupez plusieurs commerces sous un programme de fidélité mutualisé.",
      partnerFeatures: ["Gestion multi-commerces", "Fidélité partagée", "Offres communes", "Vision globale KPIs"],
      partnerBadge: "Extension évolutive",
      viewClient: "Voir la vue client",
      openDashboard: "Ouvrir le dashboard",
      viewModule: "Voir le module",
      stepsTitle: "Comment ça marche ?",
      stepsSub: "Un processus simple en 5 étapes",
      steps: [
        { emoji: "🛒", label: "Achat",          desc: "Le client effectue un achat" },
        { emoji: "📱", label: "Scan",            desc: "Il scanne le QR code" },
        { emoji: "✅", label: "Enregistrement",  desc: "La visite est enregistrée" },
        { emoji: "⭐", label: "Points",          desc: "Les points s'accumulent" },
        { emoji: "🎁", label: "Récompense",      desc: "Cadeau + invitation avis" },
      ],
      pricingTitle: "Choisissez votre formule",
      pricingSub: "Des forfaits adaptés à chaque type de commerce, sans engagement.",
      pricingNote: "Tous les forfaits incluent 30 jours d'essai gratuit · Pas de carte bancaire requise",
      popular: "Populaire",
      ctaStart: "Commencer avec",
      currency: "TND / mois",
      featuresTitle: "Tout ce dont vous avez besoin",
      features: [
        { emoji: "📲", title: "QR Code unique",            desc: "Un code personnalisé par commerce, utilisable à la caisse ou sur les menus." },
        { emoji: "🎁", title: "Récompenses automatiques",  desc: "Configurez vos récompenses et déclenchez-les sans effort manuel." },
        { emoji: "📊", title: "Analytics avancés",         desc: "Suivez vos performances, l'évolution clients et votre chiffre d'affaires." },
        { emoji: "⭐", title: "Avis Google Maps",          desc: "Redirigez vos clients satisfaits vers Google Maps au bon moment." },
        { emoji: "👥", title: "Gestion clients",           desc: "Centralisez les données de vos clients et leur historique de visites." },
        { emoji: "🤝", title: "Programme partenaire",      desc: "Mutualisez la fidélité entre plusieurs commerces partenaires." },
      ],
      ctaTitle: "Prêt à digitaliser votre fidélisation ?",
      ctaSub: "Rejoignez les commerces de Nabeul qui font confiance à Jigoula.cards pour fidéliser leurs clients.",
      ctaFree: "Commencer gratuitement",
      ctaDemo: "Voir la démo",
      footerPfe: "Projet de Fin d'Études · PFE 2025",
      tagline: "DIGITAL LOYALTY. LOCAL GROWTH.",
    },
    auth: {
      title: "Connexion à votre espace",
      sub: "Gérez votre programme de fidélité",
      tabMerchant: "Commerçant",
      tabPartner: "Partenaire",
      emailLabel: "Email ou téléphone",
      emailPartner: "Email partenaire",
      password: "Mot de passe",
      forgot: "Mot de passe oublié ?",
      submit: "Accéder au dashboard",
      back: "← Retour à l'accueil",
      demoTitle: "Mode démo",
      demoSub: "Identifiants pré-remplis, cliquez directement sur Accéder",
    },
    client: {
      scanOk: "Visite enregistrée avec succès !",
      back: "Retour",
      visits: "visites",
      since: "Client depuis",
      loyaltyCard: "Carte de fidélité",
      collectVisits: "Collectez {n} visites",
      stampsProgress: "{cur}/{total} visites",
      rewards: "Récompenses disponibles",
      presentCounter: "À présenter à la caisse",
      stillNeeded: "Encore {n} visite(s) pour débloquer votre récompense",
      history: "Historique des visites",
      reviewTitle: "Comment était votre visite ?",
      reviewSub: "Merci pour votre {n}ème visite ! 🎉 Votre avis aide d'autres clients à nous découvrir.",
      reviewBtn: "Laisser un avis sur Google Maps",
      reviewDone: "Merci pour votre avis !",
      reviewDoneSub: "Votre feedback nous aide à nous améliorer.",
      poweredBy: "Propulsé par Jigoula.cards",
      visitLabel: "Visite enregistrée",
      rewardUsed: "Récompense utilisée 🎁",
    },
    merchant: {
      overview: "Tableau de bord",
      clients: "Clients",
      loyalty: "Programme",
      qrcode: "QR Code",
      reviews: "Avis clients",
      totalClients: "Clients totaux",
      monthVisits: "Visites ce mois",
      rewards: "Récompenses",
      googleReviews: "Avis Google",
      recentActivity: "Activité récente",
      manageClients: "Gestion des clients",
      search: "Rechercher...",
      add: "Ajouter",
      programType: "Type de programme",
      stamps: "Tampons",
      points: "Points",
      preview: "Aperçu client",
      yourQr: "Votre QR Code",
      displayQr: "Affichez ce code à la caisse",
      download: "Télécharger",
      preview2: "Aperçu",
      reviewConfig: "Configuration des avis",
      reviewConfigSub: "Automatisez les demandes d'avis Google Maps",
      reviewStats: "Statistiques des avis",
      save: "Sauvegarder",
      saved: "✓ Sauvegardé !",
    },
    partner: {
      groupName: "Groupe Nabeul Commerce",
      groupSub: "Partenariat multi-enseignes · Nabeul, Tunisie",
      addShop: "Ajouter un commerce",
      extension: "Extension évolutive",
      totalClients: "Clients totaux",
      totalVisits: "Visites totales",
      rewards: "Récompenses",
      retention: "Taux rétention",
      myShops: "Mes commerces",
      merchantView: "Vue commerçant",
      visitsByShop: "Visites par commerce",
      clientShare: "Répartition clients",
      topClients: "Top clients fidèles",
      perfByShop: "Performance par commerce",
      sharedOffers: "Offres communes",
      sharedOffersSub: "Programmes partagés entre vos commerces",
      newOffer: "Nouvelle offre",
      noteTitle: "Module Partenaire — Extension Évolutive",
      noteSub: "Le module partenaire est conçu comme une extension stratégique de Jigoula.cards, permettant aux commerces de mutualiser leurs programmes de fidélité et d'offrir une expérience client unifiée à travers plusieurs enseignes.",
    },
  },

  ar: {
    nav: {
      client: "عرض العميل",
      merchant: "التاجر",
      partner: "الشريك",
      login: "تسجيل الدخول",
      partnerSpace: "فضاء الشريك",
      merchantSpace: "فضاء التاجر",
      logout: "تسجيل الخروج",
    },
    landing: {
      badge: "متاح الآن — نابل، تونس",
      heroTitle: "الولاء الرقمي",
      heroAccent: "المُعاد ابتكاره",
      heroTitle2: "لتجارتك المحلية",
      heroSub: "استبدل بطاقات الورق بحل رقمي عصري. QR كود ونقاط ومكافآت — كل شيء في مكان واحد، بدون تحميل.",
      cta1: "عرض لوحة التحكم",
      cta2: "عرض العميل",
      stat1: "زيادة في الزيارات المتكررة",
      stat2: "تحميل مطلوب",
      stat3: "للبدء",
      problemTitle: "تجارتك المحلية تستحق أفضل",
      problemSub: "الأساليب التقليدية لم تعد تعمل في اقتصاد اليوم الرقمي.",
      problems: [
        { icon: "📋", title: "بطاقات ورقية ضائعة", desc: "يفقد العملاء بطاقاتهم ويفقد التجار عملاءهم." },
        { icon: "📊", title: "لا بيانات عن العملاء", desc: "يستحيل فهم جمهورك أو تخصيص العروض لهم." },
        { icon: "👁️", title: "رؤية محدودة", desc: "لا آراء على الإنترنت، يصعب جذب عملاء جدد." },
      ],
      actorsTitle: "حل لكل طرف",
      actorsSub: "تربط Jigoula.cards العملاء والتجار والشركاء في منظومة ولاء رقمية.",
      clientRole: "العميل",
      clientTitle: "ولاء بلا تعقيد",
      clientDesc: "امسح رمز QR واستفد من امتيازاتك دون تنزيل أي تطبيق.",
      clientFeatures: ["مسح QR فوري", "متابعة النقاط والختم", "مكافآت تلقائية", "دعوة لتقييم Google"],
      merchantRole: "التاجر",
      merchantTitle: "لوحة تحكم شاملة",
      merchantDesc: "أدر برنامج الولاء الخاص بك وحلل أداءك من لوحة تحكم سهلة الاستخدام.",
      merchantFeatures: ["إحصاءات وتحليلات", "إدارة العملاء", "رمز QR فريد", "نقاط أو ختم", "آراء Google Maps"],
      partnerRole: "الشريك",
      partnerTitle: "متعدد الفروع",
      partnerDesc: "اجمع عدة تجارات تحت برنامج ولاء موحد.",
      partnerFeatures: ["إدارة متعددة الفروع", "ولاء مشترك", "عروض مشتركة", "رؤية شاملة للمؤشرات"],
      partnerBadge: "توسّع تدريجي",
      viewClient: "عرض واجهة العميل",
      openDashboard: "فتح لوحة التحكم",
      viewModule: "عرض الوحدة",
      stepsTitle: "كيف يعمل النظام؟",
      stepsSub: "عملية بسيطة في 5 خطوات",
      steps: [
        { emoji: "🛒", label: "شراء",   desc: "يقوم العميل بعملية شراء" },
        { emoji: "📱", label: "مسح",    desc: "يمسح رمز QR الخاص بالتاجر" },
        { emoji: "✅", label: "تسجيل", desc: "يتم تسجيل الزيارة تلقائياً" },
        { emoji: "⭐", label: "نقاط",   desc: "تتراكم النقاط تدريجياً" },
        { emoji: "🎁", label: "مكافأة", desc: "مكافأة + دعوة لتقييم التجربة" },
      ],
      pricingTitle: "اختر خطتك",
      pricingSub: "خطط مصممة لكل نوع من التجارة، بدون التزام.",
      pricingNote: "جميع الخطط تشمل 30 يوم تجريبي مجاني · لا يلزم بطاقة بنكية",
      popular: "الأكثر طلباً",
      ctaStart: "ابدأ مع",
      currency: "د.ت / شهر",
      featuresTitle: "كل ما تحتاجه",
      features: [
        { emoji: "📲", title: "رمز QR فريد",         desc: "رمز مخصص لكل تجارة، يمكن استخدامه عند الصندوق أو على القائمة." },
        { emoji: "🎁", title: "مكافآت تلقائية",       desc: "أعدّ مكافآتك وشغّلها تلقائياً دون أي جهد يدوي." },
        { emoji: "📊", title: "تحليلات متقدمة",        desc: "تابع أداءك وتطور العملاء ورقم أعمالك." },
        { emoji: "⭐", title: "آراء Google Maps",      desc: "وجّه عملاءك الراضين إلى Google Maps في الوقت المناسب." },
        { emoji: "👥", title: "إدارة العملاء",         desc: "مركّز بيانات عملائك وسجل زياراتهم في مكان واحد." },
        { emoji: "🤝", title: "برنامج الشراكة",        desc: "اجمع برامج الولاء بين عدة تجارات شريكة." },
      ],
      ctaTitle: "مستعد لرقمنة ولاء عملائك؟",
      ctaSub: "انضم إلى تجارات نابل التي تثق بـ Jigoula.cards لتفعيل برامج الولاء وزيادة الإيرادات.",
      ctaFree: "ابدأ مجاناً",
      ctaDemo: "عرض تجريبي",
      footerPfe: "مشروع تخرج · PFE 2025",
      tagline: "الولاء الرقمي. النمو المحلي.",
    },
    auth: {
      title: "تسجيل الدخول إلى فضائك",
      sub: "أدر برنامج الولاء الخاص بك",
      tabMerchant: "التاجر",
      tabPartner: "الشريك",
      emailLabel: "البريد الإلكتروني أو الهاتف",
      emailPartner: "بريد الشريك الإلكتروني",
      password: "كلمة المرور",
      forgot: "نسيت كلمة المرور؟",
      submit: "الدخول إلى لوحة التحكم",
      back: "← العودة إلى الرئيسية",
      demoTitle: "وضع تجريبي",
      demoSub: "البيانات مُعبأة مسبقاً، انقر مباشرة على الدخول",
    },
    client: {
      scanOk: "تم تسجيل الزيارة بنجاح!",
      back: "رجوع",
      visits: "زيارات",
      since: "عميل منذ",
      loyaltyCard: "بطاقة الولاء",
      collectVisits: "اجمع {n} زيارات",
      stampsProgress: "{cur}/{total} زيارات",
      rewards: "المكافآت المتاحة",
      presentCounter: "قدّمها عند الصندوق",
      stillNeeded: "بقي {n} زيارة لفتح مكافأتك",
      history: "سجل الزيارات",
      reviewTitle: "كيف كانت زيارتك؟",
      reviewSub: "شكراً على زيارتك رقم {n}! 🎉 تقييمك يساعد عملاء آخرين على اكتشافنا.",
      reviewBtn: "اترك تقييماً على Google Maps",
      reviewDone: "شكراً على تقييمك!",
      reviewDoneSub: "ملاحظاتك تساعدنا على التحسين.",
      poweredBy: "مدعوم بـ Jigoula.cards",
      visitLabel: "زيارة مسجّلة",
      rewardUsed: "مكافأة مستخدمة 🎁",
    },
    merchant: {
      overview: "لوحة التحكم",
      clients: "العملاء",
      loyalty: "البرنامج",
      qrcode: "QR كود",
      reviews: "آراء العملاء",
      totalClients: "إجمالي العملاء",
      monthVisits: "الزيارات هذا الشهر",
      rewards: "المكافآت",
      googleReviews: "آراء Google",
      recentActivity: "النشاط الأخير",
      manageClients: "إدارة العملاء",
      search: "بحث...",
      add: "إضافة",
      programType: "نوع البرنامج",
      stamps: "ختم",
      points: "نقاط",
      preview: "معاينة العميل",
      yourQr: "رمز QR الخاص بك",
      displayQr: "اعرض هذا الرمز عند الصندوق",
      download: "تحميل",
      preview2: "معاينة",
      reviewConfig: "إعداد آراء العملاء",
      reviewConfigSub: "أتمتة طلبات تقييم Google Maps",
      reviewStats: "إحصاءات التقييمات",
      save: "حفظ",
      saved: "✓ تم الحفظ!",
    },
    partner: {
      groupName: "مجموعة تجارة نابل",
      groupSub: "شراكة متعددة الفروع · نابل، تونس",
      addShop: "إضافة تجارة",
      extension: "توسّع تدريجي",
      totalClients: "إجمالي العملاء",
      totalVisits: "إجمالي الزيارات",
      rewards: "المكافآت",
      retention: "معدل الاحتفاظ",
      myShops: "تجاراتي",
      merchantView: "واجهة التاجر",
      visitsByShop: "الزيارات حسب التجارة",
      clientShare: "توزيع العملاء",
      topClients: "أوفى العملاء",
      perfByShop: "الأداء حسب التجارة",
      sharedOffers: "العروض المشتركة",
      sharedOffersSub: "البرامج المشتركة بين تجاراتك",
      newOffer: "عرض جديد",
      noteTitle: "وحدة الشريك — توسّع تدريجي",
      noteSub: "صُمِّمت وحدة الشريك كامتداد استراتيجي لـ Jigoula.cards، تتيح للتجارات تجميع برامج الولاء وتقديم تجربة عميل موحدة عبر فروع متعددة.",
    },
  },
} as const;

type Translations = typeof translations.fr;

interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: Translations;
  dir: 'ltr' | 'rtl';
}

const LangContext = createContext<LangContextType>({
  lang: 'fr',
  setLang: () => {},
  t: translations.fr,
  dir: 'ltr',
});

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>('fr');

  useEffect(() => {
    const dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.dir = dir;
    document.documentElement.lang = lang;
  }, [lang]);

  const t = translations[lang] as unknown as Translations;
  const dir = lang === 'ar' ? 'rtl' : 'ltr';

  return (
    <LangContext.Provider value={{ lang, setLang, t, dir }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
